Repository GitHub-for-Devs/day-1-caption-this, pull requests merged in 2024-04, with the labels that each got.

#12 update caption
  _slides/14-fbiedil.md
Labels: documentation

#24 Add caption steffenvollan
  _slides/23-steffenvollan.md
Labels: documentation, duplicate

#23 The standard octocat wasnt cutting it, we need investocat
  _slides/25-trep8.md
Labels: enhancement

#11 Update caption
  _slides/03-PuneetKMinhas.md
Labels: documentation, enhancement
